services:
  app:
    build:
      context: .
      args:
        APP_VERSION: ${APP_VERSION:-dev}
        GIT_SHA: ${GIT_SHA:-local}
    image: tiny-devops-service:local
    ports:
      - "8002:8000"
    environment:
      APP_VERSION: ${APP_VERSION:-dev}
      GIT_SHA: ${GIT_SHA:-local}
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request;urllib.request.urlopen('http://127.0.0.1:8000/healthz')"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
