{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tiny-devops-service.fullname" . }}-secret
  labels:
    {{- include "tiny-devops-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  EXAMPLE_TOKEN: {{ .Values.secret.exampleToken | quote }}
{{- end }}
